version: "3"
services:
    pryv_api:
        image:  pryvio/open-pryv.io:1.5.18
        command: "yarn api"
        container_name: "pryv_api"
        restart: "always"
        links:
            - pryv_mongo
        depends_on:
            - pryv_mongo
        networks:
          - app-network
          
    pryv_mail:
        image:  pryvio/open-pryv.io:1.5.18
        command: "yarn mail"
        container_name: "pryv_mail"
        restart: "always"
        depends_on:
            - pryv_api
        volumes:
          - ./var-pryv/logs/:/app/var-pryv/logs/
          - ./configs/dockerized-service-mail-config.hjson:/app/service-mail/config.hjson
        networks:
          - app-network
          
    pryv_mongo:
        image: mongo:3.6.18
        container_name: "pryv_mongo"
        restart: "always"
        volumes:
            - ./var-pryv/mongodb/conf/:/app/conf/:ro
            - ./var-pryv/mongodb/data/:/app/data/
            - ./var-pryv/mongodb/log/:/app/log/
            - ./var-pryv/mongodb/backup/:/app/backup/
        networks:
          - app-network
          
    # visualize data in mongodb - only for local development
    mongo-express: 
      image: mongo-express
      restart: "always"
      ports:
        - 8081:8081
      environment:
          ME_CONFIG_MONGODB_SERVER: pryv_mongo
      networks:
          - app-network
          
    pryv_nginx:
        image: nginx:latest
        container_name: "pryv_nginx"
        volumes:
          - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
          - ./configs/site.conf:/etc/nginx/site.conf
          - ./configs/rec.la-certificates/src/:/etc/nginx/certs/self-signed/
          - ./configs/dhparam.pem:/etc/nginx/certs/dhparam.pem
        ports:
          - 80:80
          - 443:443
        links:
          - pryv_api
          - pryv_mail
        depends_on:
          - pryv_api
          - pryv_mail
        networks:
          - app-network
        environment:
          - PUBLIC_URL=my-computer.rec.la

networks:
  app-network:
    driver: bridge    
