version: "3.8"
services:
  open-pryv.io:
    build: 
      context: ../..
      dockerfile: ./docker/local/Dockerfile
    image: pryvio/open-pryv.io:${TAG}
    command: "yarn api"
    container_name: "open-pryv.io"
    restart: "always"
    volumes:
      - ./dockerized-config.yml:/app/config.yml
      - ../../public_html/:/app/public_html/
      - ../../var-pryv/core/data/:/app/data/
    depends_on:
      - open-pryv-mongo
    networks:
      - app-network

  open-pryv-mail:
    image: pryvio/open-pryv.io:${TAG}
    command: "/bin/sh /app/mail.sh"
    container_name: "open-pryv-mail"
    restart: "always"
    depends_on:
      - open-pryv.io
    volumes:
      - ../../var-pryv/logs/:/app/var-pryv/logs/
      - ./dockerized-service-mail-config.hjson:/app/service-mail/config.hjson
    networks:
      - app-network

  open-pryv-mongo:
    image: mongo:6.0.5
    container_name: "open-pryv-mongo"
    restart: "always"
    volumes:
      - ../../var-pryv/mongodb/data/:/data/db/
      - ../../var-pryv/mongodb/backup/:/data/backup/
    networks:
      - app-network

  open-pryv-nginx:
    container_name: "open-pryv-nginx"
    image: nginx:latest
    volumes:
      # You can load custom nginx config and use env variables in it
      - ./nginx-templates:/etc/nginx/templates
      # Load default *.rec.la (or your) certificates
      - ../../rec.la-certificates/src/rec.la-bundle.crt:/etc/letsencrypt/live/my-computer.rec.la/fullchain.pem
      - ../../rec.la-certificates/src/rec.la-key.pem:/etc/letsencrypt/live/my-computer.rec.la/privkey.pem
      - ./dhparam.pem:/etc/letsencrypt/ssl-dhparams.pem
    ports:
      - 80:80
      - 4443:4443
    depends_on:
      - open-pryv.io
      - open-pryv-mail
    networks:
      - app-network
    environment:
      - PORT=80
      - PORT_SSL=4443
      - HOSTNAME=my-computer.rec.la
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx

networks:
  app-network:
    driver: bridge
